[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/run/supervisord.pid

[program:php-fpm]
command=/usr/sbin/php-fpm8.1 -F --nodaemonize --fpm-config /etc/php/8.1/fpm/php-fpm.conf
priority=10
autostart=true
autorestart=true
stopsignal=QUIT
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/bin/sh -c "if [ ! -f /etc/letsencrypt/live/litrep.ru/fullchain.pem ]; then mkdir -p /etc/letsencrypt/live/litrep.ru; openssl req -x509 -nodes -newkey rsa:2048 -days 1 -keyout /etc/letsencrypt/live/litrep.ru/privkey.pem -out /etc/letsencrypt/live/litrep.ru/fullchain.pem -subj '/CN=litrep.ru'; fi; exec /usr/sbin/nginx -g 'daemon off;'"
priority=20
autostart=true
autorestart=true
stopsignal=QUIT
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


[program:certbot-renew]
command=/bin/sh -c "while true; do certbot renew --webroot -w /var/www/certbot --quiet --deploy-hook 'nginx -s reload'; sleep 12h; done"
priority=30
autostart=true
autorestart=true
stopsignal=TERM
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0


